# Cast

Here is an overview of the notable cast members you have met so far.

**Angus 'Gus' Augustus ‘Gus’ Fleetfoot.** 
*Let me tell you the first rule of business. There are no rules.* 
Landlord. Halfling man in his early 100s. Handle bar moustache as well waxed as his hair.

**Sweetie Fleetfoot.**
Goliath Chef. Wife of Gus. White chefs clothes and huge rolling pin. Produces tiny finger food. Tussles Gus’s hair whenever she goes past.

**Clover Fleetfoot.** 
*Whatever Dad.*
Human sized. Gus’s daughter and waitress. Surly teenager but well doing their best with the public.



Grog. Drunk man in the corner. He is actually Kwo Carm, member of the sage’s landing secret service - watching for the arms deal Gus is making. Perception +6, Deception +6, Slight of hand +6. He has a tankard of sobriety that he is drinking from.
Grog!

Kootakaar Falsari. Gnome forger. Koot is wearing many googles and quills. dex +2 slight of hand +4. Very scared of Martyn Oliver
Yes, yup.

Arrnet Brrnogh. Orc rat catcher (armenian). Pissed off with the job he has been conned into doing.
Fuck this! Them aint no rats, owlbear cubs more like. You’ve got a problem for sure but you’re gonna need more coin than what your offern.

Sir Martyn Oliver. Deputy assistant inspector. Prone to monologuing, lover of rules. Level 5 Bard. 
This great city of Sage’s Landing is built upon beauty of the written word. A current and accurate picture of all adventurers within the city walls enables the safety of the city. Any aggressors will know that though our standing arming is small, the amount of sell swords and wands raisable from the adventurer community is vast so it is with that in mind that i ask to check the necessary paperwork…

Goodur Gaur. Assistant paperwork checker. Thinks his boss is a jerk. Will help the PCs avoid detection and take a bribe if necessary. Will work hard for them not to be caught.
Fucks sake, sorry about Sir Oliver, he’s got a hard on for parchment work if you know what I mean.

